### ISSUE TITLE
Vehicle software version 0.030, unable to register 

### ISSUE THREAD

**Issue by dstroem** [papawattu/phev-core#3]
I'm running phevctl on raspbian/raspberrypi 3 connected to car wifi. 
I'm not able to register even though there is only 1 device registered 

Can someone verify if they have connected to this vehicle software version 0.030.

**Comment by papawattu** [comment]
Hi, 

Registration is not working with the newer MY17 + models due to the encryption used.  To get it to work currently is to register a phone first, then use macchanger on the pi to change the wifi MAC address to the same as the phones. You may have more success with that, however there are still a lot of bugs I am fixing at the moment around this.

Jamie.

**Comment by papawattu** [comment]
Try again with the latest build, you may need to clear all registered devices first.

WiFi Reset Procedure:
1. Get in the car and Fully close the Drivers door.
2. IMPORTANT - All steps below must be performed within a total of 30 seconds.
3. Without pressing the brake pedal, press the power button once so that it glows orange (ACC mode).
4. Turn on the Hazard lights.
5. Now quickly alternately press and release the LOCK and UNLOCK buttons on the key fob 5 times, i.e. 10 presses in total. This must be done within 10 seconds of pressing the Power button ON as in (1) above.
6. Listen for one BEEP, followed by 0, 1 or 2 more beeps.
7. Now quickly alternately press the LOCK and UNLOCK buttons on the key fob another 10 times each within 10 seconds, i.e. another 20 presses.
8. Listen for one BEEP, followed by 0 more beeps.

**Comment by dstroem** [comment]
Tried to build now, but I get

 phevcore/src/phev.c: In function ‘phev_createIncomingMessageClient’:
/home/pi/source/phevcore/src/phev.c:122:9: error: unknown field ‘disconnect’
...
phevcore/src/phev.c:140:9: error: unknown field ‘disconnect’ specified in initializer

**Comment by papawattu** [comment]
Hi, have you updated to the latest version this and msg_core?

**Comment by clusterice** [comment]
Hi
I also receive an error when i compile the phevcore:

```
_________/phevcore/src/phev.c:122:10: error: ‘messagingSettings_t’ {aka ‘struct messagingSettings_t’} has no member named ‘disconnect’; did you mean ‘connect’?
  122 |         .disconnect = NULL,
      |          ^~~~~~~~~~
      |          connect


____/phevcore/src/phev.c:140:10: error: ‘tcpIpSettings_t’ {aka ‘struct tcpIpSettings_t’} has no member named ‘disconnect’; did you mean ‘connect’?
  140 |         .disconnect = phev_tcpClientDisconnectSocket,
      |          ^~~~~~~~~~
      |          connect
```

I using Ubuntu 20.04 and tried compile everything normaly and also in the docker. Both versions results in this problem.

**Comment by dstroem** [comment]
I have updated all and get the same error as clusterice

**Comment by papawattu** [comment]
Apologies, I hadn't pushed the changes to msg_core, pull the latest updates and rebuild and install msg_core.

**Comment by dstroem** [comment]
Now it builds ok, but I get segmentation fault when I try to register

**Comment by papawattu** [comment]
can you post the output of` git describe` please

**Comment by dstroem** [comment]
I'm sorry I'm not familiar with the describe command when I run git describe I get
"fatal: No names found, cannot describe anything".

**Comment by papawattu** [comment]
I've just pushed a new version, `git pull && git checkout v0.1`

**Comment by RogerG007** [comment]
I have the same compile error as @clusterrice above. The output from `git describe` says v0.1.
Any ideas on how to get it compiled?

**Comment by papawattu** [comment]
can you try installing from scratch, both msg_core and phevcore please, I have just done the same and not getting any issues.

**Comment by RogerG007** [comment]
Thanks. Installing everything from scratch helped!

**Comment by Comsystems** [comment]
Hi all,

I build phevctl without errors based on the latest source-versions, but unfortunately register my Outlander (2019) dosen't work , even though initial connect seems to work (see log-file [DEBUG-mode]) 
[register.log](https://github.com/phev-remote/phevcore/files/5037474/register.log)

Suprisingly "headlights on/off" afterwords can be used in the same session with success and correct reaktion of the car (lights turn on/off) even though no device is registered. Other functions don' work and in DEBUG-mode connection to server failed  is logged.

I tryed register procedure also after compete removal of all registered devices, but doesn't work either.
Don't know vehicle software version.

I'm very interested to successfully set up this great project.
Jamie, do you have any idea or can help me ?

Thanks Jan

**Comment by dstroem** [comment]
I'm able to connect now so closing the issue.
